
void Triangle_interaction();
void Square_interaction();
void Rectangle_interaction();
void Line_interaction();
void Diamond_interaction();
void Pyramid_interaction();
void trapezium_interaction();
void parallelogram_interaction();
void pentagon_interaction();
void hexagon_interaction();
void heart_interaction();
void circle_interaction();
void oval_interaction();
void kite_interaction();
void chatbox_interaction();
void number_interaction();
void arrow_interaction();
void alphabets_interaction();
void custom_shape(int select);
void Ms_paint(int choose);
void paint_interaction();
void draw_on_terminal();
void savingfile_interaction();
void save();
void existingfile_interaction();
void existfile();
void editfile_interaction();
void editfile();
void Main_menu();
void filesexist_input();
void print_file_contents(const char *filename);
void fileEdit_input();
void over_input();
void triangle_s();
void square_s();
void rectangle_s();
void diamond_s();
void saved_file(int option);
void saving_shape(int select);